# action.yaml
name: 'WordPress Readme.txt Generator'
description: 'Creates the readme.txt file from plugin/theme metadata'
author: 'Sixa'
branding:
  icon: chevron-right
  color: black
inputs:
  input_path:
    description: 'Relative path to WordPress plugin/theme main file to get metadata from'
  project_type:
    description: 'Type of the project - can be either `theme` or `plugin`'
  replace:
    description: 'Delete existing README.md and put readme.txt instead'
    default: false
  output_path:
    description: 'Relative path to dir_path where readme.txt should be placed'
    default: './readme.txt'
runs:
      using: 'node12'
      main: 'dist/index.js'